clusterGroup:
  name: hub

  subscriptions:
    talm:
      name: topology-aware-lifecycle-manager

  applications:
    acm:
      name: acm
      namespace: default
      project: default
      kustomize: true
      path: kustomize/overlays/acm
